name: Deploy to Firebase Hosting on Merge
on:
  push:
    branches: [ main ]  # Cambia a "master" si esa es tu rama principal

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build  # Opcional: si usas un build step
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: mamba-cup  # Reemplaza esto
          channelId: live